#! /bin/sh

# requires bspwm, slop

state_file="/tmp/bspwm_state.json"

bspc wm --dump-state > "$state_file"

hidden_nodes="$(bspc query --nodes --node .hidden)"
echo "$hidden_nodes" | while read -r node; do bspc node "$node" --flag hidden=off; done

bspc monitor --reset-desktops "Pick a Node"
bspc desktop --layout tiled
bspc node @/ --focus --balance

window_id=$(slop --highlight --tolerance 9999999 --color 0.27,0.52,0.533,0.2 --format %i)

echo "$hidden_nodes" | while read -r node; do bspc node "$node" --flag hidden=on; done

bspc wm --load-state "$state_file"

# this script doesn't really work because {dump,load}-state
# don't do what I expect, so we need to trigger recalculation
# of window dimensions:
bspc config window_gap $(bspc config window_gap)
bspc query --nodes --node '.window.!hidden' | while read -r node; do
    bspc node $node --focus
done

bspc node "$window_id" --flag hidden=off
bspc node "$window_id" --focus
