#! /bin/dash

# uses chbpresel to use borders as preselection indication on leaf nodes
# chbpresel is from https://github.com/neeasade/opt

dir="$1"
node="$2"
focused_color=$(bspc config focused_border_color)

if [ "$dir" = "cancel" ]; then
    chbpresel -C "${focused_color#?}" -c "${focused_color#?}" -d 1 "$node"
    bspc node $node --presel-dir "$dir"
    bspc config presel_feedback true

elif bspc query --nodes --node $node.leaf > /dev/null; then
    bspc config presel_feedback false
    case $dir in
        north) dir_num=1 ;;
        east)  dir_num=4 ;;
        south) dir_num=3 ;;
        west)  dir_num=2 ;;
    esac
    presel_color=$(bspc config presel_feedback_color)
    chbpresel -C "${presel_color#?}" -c "${focused_color#?}" -d "$dir_num" "$node"
    bspc node $node --presel-dir "$dir"

else
    bspc config presel_feedback true
    bspc node $node --presel-dir "$dir"
fi

