#!/bin/sh

# STARTUP

swaybg -m fill -i ~/wallpaper &
mako &
foot --server &
swayidle -w \
    timeout 600  "swaylock -f -c '#282828'" \
    before-sleep "swaylock -f -c '#282828'" &


mod="Mod4"

# BASIC MAPPINGS

riverctl map normal $mod Return spawn footclient
riverctl map normal $mod Space  spawn runner

riverctl map normal $mod S toggle-float
riverctl map normal $mod F toggle-fullscreen

riverctl map normal $mod D close

riverctl map normal $mod G zoom

riverctl map normal $mod H mod-main-factor -0.05
riverctl map normal $mod L mod-main-factor +0.05

riverctl map normal $mod+Shift H mod-main-count +1
riverctl map normal $mod+Shift L mod-main-count -1

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

riverctl map normal $mod X spawn "swaylock -c '#282828'"

riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

layouts="/tmp/river_layouts"
cat > $layouts << EOF
full
rtab
rivertile left
EOF
riverctl map normal $mod M spawn 'riverctl layout "$(head -1 '"$layouts"'; sed -i "1{H;1h;d};\$G" '"$layouts"')"'


# TAG MAPPINGS

for i in $(seq 1 9); do

    tags=$((1 << (i - 1)))

    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $tags
riverctl map normal $mod+Shift 0 set-view-tags $tags
riverctl map normal $mod+Control 0 toggle-focused-tags $tags
riverctl map normal $mod+Shift+Control 0 toggle-view-tags $tags



# FLOATING MAPPINGS

riverctl declare-mode floating
riverctl map normal $mod Z enter-mode floating
riverctl map floating $mod Z enter-mode normal

riverctl map floating $mod J focus-view next
riverctl map floating $mod K focus-view previous

riverctl map floating $mod D close

riverctl map floating $mod+Mod1 H move left  100
riverctl map floating $mod+Mod1 J move down  100
riverctl map floating $mod+Mod1 K move up    100
riverctl map floating $mod+Mod1 L move right 100

riverctl map floating $mod+Control H snap left
riverctl map floating $mod+Control J snap down
riverctl map floating $mod+Control K snap up
riverctl map floating $mod+Control L snap right

riverctl map floating $mod+Shift H resize horizontal -100
riverctl map floating $mod+Shift J resize vertical    100
riverctl map floating $mod+Shift K resize vertical   -100
riverctl map floating $mod+Shift L resize horizontal  100

riverctl map floating $mod S toggle-float
riverctl map floating $mod F toggle-fullscreen

riverctl map-pointer floating $mod BTN_LEFT move-view
riverctl map-pointer floating $mod BTN_RIGHT resize-view


# SHORTCUT KEY MAPPINGS

for mode in normal locked floating; do
    riverctl map $mode None XF86AudioMute        spawn volume_change --toggle-mute
    riverctl map $mode None XF86AudioLowerVolume spawn volume_change -d 5
    riverctl map $mode None XF86AudioRaiseVolume spawn volume_change -i 5

    riverctl map $mode None XF86AudioPlay spawn playerctl play-pause
    riverctl map $mode None XF86AudioPrev spawn playerctl previous
    riverctl map $mode None XF86AudioNext spawn playerctl next

    riverctl map $mode None XF86MonBrightnessUp   spawn brightness_change -A 5
    riverctl map $mode None XF86MonBrightnessDown spawn brightness_change -U 5

    riverctl map $mode None Print spawn 'grim -g "$(slurp)"'
done


# CONFIG

riverctl set-repeat 50 400

riverctl border-width 0
riverctl opacity 1 0.85 0.7 0.1 0.1
riverctl attach-mode top

riverctl layout rivertile left
